export const NEW_BOOKING_SUCCESS = "NEW_BOOKING_SUCCESS";
export const NEW_BOOKING_FAIL = "NEW_BOOKING_FAIL";
export const GET_BOOKING_SUCCESS = "NEW_BOOKING_SUCCESS";
export const GET_BOOKING_FAIL = "NEW_BOOKING_FAIL";
export const GET_BOOKING_LOADING = "GET_BOOKING_LOADING"