export const REGISTRE_SUCCESS = "REGISTRE_SUCCESS";
export const REGISTRE_FAIL = "REGISTRE_FAIL";
export const REGISTRE_LOADING = "REGISTRE_LOADING";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const GET_ALL_USERS_LOADING = "GET_ALL_USERS_LOADING";

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";

export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const DETAIL_USER_FAIL = "DETAIL_USER_FAIL";
export const DETAIL_USER_SUCCESS = "DETAIL_USER_SUCCESS";

export const LOGOUT = "LOGOUT";